name: py4fi
channels:
  - defaults
dependencies:
  - scikit-learn
  - anywidget
  - pyyaml
  - scipy
  - openpyxl
  - matplotlib
  - jupyter
  - numba
  - numpy
  - sympy
  - pytables
  - ipython
  - pandas
  - python=3.13.14
  - notebook
  - cython
  - statsmodels
  - pymc
  - arviz[version='>=1.2.0']
  - arviz-plots[version='>=1.2.0']
  - tensorflow
  - pip
  - pip:
      - plotly
      - cufflinks
      - colorlover
